#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom

# Repo init command, that -device,-mips,-darwin,-notdefault part will save you more time and storage to sync, add more according to your rom and choice. Optimization is welcomed! Let's make it quit, and with depth=1 so that no unnecessary things.
repo init -u https://github.com/Wave-Project/manifest -b r -g default,-device,-mips,-darwin,-notdefault

# Sync source with -q, no need unnecessary messages, you can remove -q if want! try with -j30 first, if fails, it will try again with -j8
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 30 || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j 8

# Clone local manifest! So that no need to manually git clone repos or change hals, you can use normal git clone or rm and re clone, they will cost little more time, and you may get timeout! Let's make it quit and depth=1 too.
#git clone https://github.com/Apon77Lab/android_.repo_local_manifests.git --depth 1 -b aex .repo/local_manifests
git clone https://github.com/KharaMe-devices/android_device_realme_RMX1971 -b eleven device/realme/RMX1971
git clone https://github.com/KharaMe-devices/android_device_realme_sdm710-common -b eleven device/realme/sdm710-common
git clone https://github.com/KharaMe-devices/android_kernel_realme_sdm710 -b eleven kernel/realme/RMX1971
git clone https://gitlab.com/bablusss/vendor_realme_RMX1971 -b eleven vendor/realme/RMX1971
git clone https://gitlab.com/bablusss/vendor_realme_sdm710-common -b eleven vendor/realme/sdm710-common
sed -i '12d' hardware/qcom-caf/sdm845/display/Android.mk
cd device/realme/RMX1971 && mv aosp_RMX1971.mk lineage_RMX1971.mk
sudo apt-get install wget grep
grep -rl aosp . | xargs sed -i 's/aosp/lineage/g'
cd overlay/frameworks/base/core/res/res/values && rm config.xml && wget http://kontena.aikara.me/0:/config.xml
cd ../../../../../../../../../..